# Travis CI (MIT License) configuration file for the BP-REST
# @link https://travis-ci.org/

# Setting dist.
dist: xenial

# Setting OS.
os: linux

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Setting services.
services:
  - mysql

branches:
  only:
    - master
    - main

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Git clone depth.
git:
  depth: 1
  quiet: true

env:
  global: PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: WP_VERSION=master PHPCS=1 BUILD=1
    - php: 7.4
      env: WP_VERSION=5.4
    - php: 7.4
      env: WP_VERSION=5.3
    - php: 7.3
      env: WP_VERSION=master PHPCS=1 BUILD=1
    - php: 7.3
      env: WP_VERSION=5.4
    - php: 7.3
      env: WP_VERSION=5.0
    - php: 7.2
      env: WP_VERSION=master
    - php: 7.2
      env: WP_VERSION=5.4
    - php: 7.2
      env: WP_VERSION=5.0
    - php: 7.2
      env: WP_VERSION=4.9
    - php: 7.1
      env: WP_VERSION=master
    - php: 7.1
      env: WP_VERSION=5.4
    - php: 7.1
      env: WP_VERSION=5.0
    - php: 7.0
      env: WP_VERSION=master
    - php: 7.0
      env: WP_VERSION=5.4
    - php: 5.6
      env: WP_VERSION=master
    - php: 5.6
      env: WP_VERSION=5.4
    - php: 5.6
      env: WP_VERSION=5.0
    - php: 5.6
      env: WP_VERSION=4.9

before_install:
  - |
    # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
    phpenv config-rm xdebug.ini || echo "Xdebug not available"

install:
  # Set up WP + BP installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - export WP_TESTS_DIR=$WP_DEVELOP_DIR/tests/phpunit
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
  - cd ..
  - mv $plugin_slug $plugin_dir
  - svn co --ignore-externals https://buddypress.svn.wordpress.org/trunk $WP_DEVELOP_DIR/src/wp-content/plugins/buddypress

  # set up tests config.
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php

  # set up database.
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

  # cd into the plugin folder.
  - cd $plugin_dir

before_script:
  # Require PHPUnit.
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
      composer require --dev phpunit/phpunit ^5;
    else
      composer require --dev phpunit/phpunit ^6;
    fi

  # Check Grunt.
  - |
    if [[ $BUILD == "1" ]]; then
      echo "Installing node 12 and npm 6 ..."
      nvm install 12
      npm i -g npm@6
      nvm install "$(jq -r '.engines.node' package.json | egrep -oe "[0-9\.]+")"
      npm i -g npm@$(jq -r '.engines.npm' package.json | egrep -oe "[0-9\.]+")
      npm install --quiet
    fi

  # Install PHP CodeSniffer and WPCS.
  - |
    if [[ "$PHPCS" == "1" ]]; then
      phpenv rehash

      ./vendor/bin/phpcs --config-set installed_paths '../../wimg/php-compatibility/,../../wp-coding-standards/wpcs/'
      ./vendor/bin/phpcs --config-set default_standard WordPress
    fi

script:
  - ./vendor/bin/phpunit;
  - ./vendor/bin/phpunit -c tests/multisite.xml;
  - find includes -type "f" -iname "*.php" -not -path "**/vendor/*" | xargs -L "1" php -l;
  - if [[ "$PHPCS" == "1" ]]; then ./vendor/bin/phpcs; fi
  - if [[ $BUILD == "1" ]]; then npm run build; fi

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
